version: "2"

linters:
    enable:
        - durationcheck
        - errcheck
        - copyloopvar
        - forcetypeassert
        - ineffassign
        - makezero
        - misspell
        - nilerr
        - predeclared
        - staticcheck
        - testifylint
        - unconvert
        - usetesting
        - unparam
        - unused
        - govet

formatters:
    enable:
        - goimports

run:
    timeout: 5m
    tests: true
    allow-parallel-runners: true
