issues:
    max-issues-per-linter: 0
    max-same-issues: 0
    exclude-rules:
        - path: '(.+)_test\.go'
          linters:
              - errcheck
          # disabling both of these for the SDKv2-based code as it's idomatic for the SDK
        - path: honeycombio/*
          text: "Error return value of `d.Set` is not checked"
        - path: honeycombio/*
          text: "type assertion must be checked"

linters-settings:
    goimports:
        local-prefixes: github.com/honeycombio/terraform-provider-honeycombio

linters:
    disable-all: true
    enable:
        - durationcheck
        - errcheck
        - exportloopref
        - forcetypeassert
        - goimports
        - gosimple
        - ineffassign
        - makezero
        - misspell
        - nilerr
        - predeclared
        - staticcheck
        - tenv
        - unconvert
        - unparam
        - unused
        - vet

run:
    # Prevent false positive timeouts in CI
    timeout: 5m
    tests: true
    allow-parallel-runners: true
